/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#7a2c38',
        secondary: '#006d36',
        'on-background': '#181d18',
        'secondary-fixed-dim': '#73dc91',
        'surface-container': '#ebefe8',
        'on-tertiary-container': '#ffcace',
        'inverse-on-surface': '#eef2eb',
        'outline-variant': '#bfc9be',
        'surface-container-highest': '#e0e4dd',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#007239',
        'on-surface': '#181d18',
        'secondary-container': '#8cf6a8',
        'primary-fixed-dim': '#87d89c',
        'tertiary-fixed-dim': '#ffb2b9',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        outline: '#6f7a70',
        'surface-variant': '#e0e4dd',
        'on-primary-fixed-variant': '#005229',
        'on-surface-variant': '#3f4940',
        'error-container': '#ffdad6',
        'on-primary-fixed': '#00210d',
        'inverse-primary': '#87d89c',
        'tertiary-fixed': '#ffdadc',
        'primary-container': '#146b3a',
        'on-error': '#ffffff',
        tertiary: '#792b38',
        background: '#f7fbf3',
        'surface-tint': '#166c3b',
        'on-error-container': '#93000a',
        'primary-fixed': '#a2f5b6',
        'surface-dim': '#d7dbd4',
        'surface-bright': '#f7fbf3',
        'inverse-surface': '#2d322d',
        primary: '#005128',
        'secondary-fixed': '#8ff9ab',
        'surface-container-high': '#e5e9e2',
        error: '#ba1a1a',
        'surface-container-low': '#f1f5ed',
        'on-primary-container': '#97e9ab',
        'on-secondary-fixed-variant': '#005227',
        'on-tertiary-fixed': '#400010',
        'tertiary-container': '#97424e',
        surface: '#f7fbf3',
        'on-secondary-fixed': '#00210c',
        'on-tertiary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '8px',
        'gutter-mobile': '16px',
        xl: '48px',
        md: '24px',
        'margin-mobile': '20px',
        sm: '16px',
        lg: '32px',
        base: '4px',
      },
      fontFamily: {
        'headline-md': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'display-lg-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
